### ISSUE TITLE
mac环境下问题

### ISSUE THREAD

**Issue by tianly123** [gengchen528/wechatBot#21]
已经npm install 
`✦6 ➜ node index.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'wechaty'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/changsheng/wechatBot/index.js:5:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
(base)`

**Comment by gengchen528** [comment]
要进入到项目目录中执行`npm install`

**Comment by tianly123** [comment]
> 要进入到项目目录中执行`npm install`

进入了

**Comment by gengchen528** [comment]
进群把报错贴一下，说明文档中有小助手的微信
