### ISSUE TITLE
运行时出现问题

### ISSUE THREAD

**Issue by chensu92** [gengchen528/wechatBot#26]
➜  workspace git:(master) ✗ npm run start

> wechatbot@0.1.1 start /root/workspace
> node index.js

10:34:56 INFO Wechaty <default> start() v0.26.1 is starting...
10:34:56 ERR PuppetPuppeteerBridge start() exception: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

10:34:56 ERR PuppetPuppeteer initBridge() exception: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

10:34:56 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
10:34:56 ERR PuppetPuppeteer start() exception: Error: Error: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.<anonymous> (/root/workspace/node_modules/wechaty/dist/src/wechaty.js:437:44)
    at PuppetPuppeteer.emit (events.js:210:5)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:475:20)
    at PuppetPuppeteer.emit (/root/workspace/node_modules/wechaty-puppet/dist/src/puppet.js:160:22)
    at PuppetPuppeteer.<anonymous> (/root/workspace/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/root/workspace/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
10:34:56 ERR Wechaty start() exception: Error: Error: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Error: Error: Error: Failed to launch chrome!
/root/workspace/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at PuppetPuppeteer.<anonymous> (/root/workspace/node_modules/wechaty/dist/src/wechaty.js:437:44)
    at PuppetPuppeteer.emit (events.js:210:5)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:475:20)
    at PuppetPuppeteer.emit (/root/workspace/node_modules/wechaty-puppet/dist/src/puppet.js:160:22)
    at PuppetPuppeteer.<anonymous> (/root/workspace/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:106:22)
    at Generator.throw (<anonymous>)
    at rejected (/root/workspace/node_modules/wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/puppet-puppeteer.js:23:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by gengchen528** [comment]
尝试重新安装一下依赖
