### ISSUE TITLE
网页版微信无法登录

### ISSUE THREAD

**Issue by haowayne** [gengchen528/wechatBot#27]
16:42:10 WARN PuppetPuppeteerBridge onDialog() page.on(dialog) type:type() {
    return this._type;
  } message:为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址 ：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
(node:11068) UnhandledPromiseRejectionWarning: Error: Error: type() {
    return this._type;
  }(为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com)
    at PuppetPuppeteer.<anonymous> (E:\wechatBot\node_modules\wechaty\dist\src\wechaty.js:436:44)
    at PuppetPuppeteer.emit (events.js:223:5)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:475:20)
    at PuppetPuppeteer.emit (E:\wechatBot\node_modules\wechaty-puppet\dist\src\puppet.js:160:22)
    at Bridge.<anonymous> (E:\wechatBot\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\puppet-puppeteer.js:210:47)
    at Bridge.emit (events.js:223:5)
    at Bridge.EventEmitter.emit (domain.js:475:20)
    at Bridge.<anonymous> (E:\wechatBot\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:131:18)
    at Generator.next (<anonymous>)
    at fulfilled (E:\wechatBot\node_modules\wechaty\node_modules\wechaty-puppet-puppeteer\dist\src\bridge.js:23:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11068) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11068) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SunSiwen2019** [comment]
是的，web版微信不能登陆了

**Comment by wbbw007** [comment]
@haowayne 目前有我们有部分API在内测阶段，具有基本的功能，我们愿意对优秀开发者、企业、学生免费开放一部分内测名额，如果您有意愿请打开下面的地址，填写相关信息，我们会审核您的资质，审核通过后将会根据您留下的联系方式联系您
https://tnwdss67qy.jiandaoyun.com/f/5e6ae0032330170006874524

**Comment by lovelyelfpop** [comment]
浏览器清除缓存，或者换个浏览器即可
